### PR TITLE
Add disableInitialValue and disableValidators options

### LINKED ISSUE #48: Plain text component has "initialValue" warning message
Checked out the code and run "yarn start". Dragged the "Plain text" component to the form builder and when something is typed into the "Initial value" text box, in the debugger there's a warning/error message. However, this is not happening in the Form Builder in the documentation site -> https://data-driven-forms.org/live-editor

Warning: React does not recognize the `initialValue` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `initialvalue` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Context.Consumer)
    in Typography (created by ResizeObserver)
    in ResizeObserver (created by LocaleReceiver)
    in LocaleReceiver (created by Base)
    in Base (created by Paragraph)
    in Paragraph (created by PlainText)
    in article (created by Context.Consumer)
    in Typography (created by PlainText)
    in PlainText (created by ComponentWrapper)
    in div (created by ComponentWrapper)
    in ComponentWrapper (created by Draggable)
    in div (created by FieldLayout)
    in div (created by FieldLayout)
    in FieldLayout (created by Draggable)
    in div (created by Draggable)
    in Draggable (created by ConnectFunction)
    in ConnectFunction (created by PrivateDraggable)
    in PrivateDraggable (created by PublicDraggable)
    in PublicDraggable
    in Unknown (created by MemoizedField)
    in MemoizedField (created by Droppable)
    in div (created by Droppable)
    in div (created by FormContainer)
    in FormContainer (created by Droppable)

### PR DESCRIPTION
**Pull request by rvsia**
fixes #48 

## componentProperties

*object*

A mapper of editable properties for each component. A property is a object with following attributes:

### attributes

Editable attributes of the component.
#### propertyName

*string*

Corresponds to an attribute in the schema.

#### label

*string*

A label shown for the property in the editor.

#### component

*string*

A component corresponding to a key in properties mapper.

### disableValidators

Disables validator selection in `PropertiesEditor`.

### disableInitialValue

Disables initial value field in `PropertiesEditor`.

### Example

```jsx
const LABEL = {
    propertyName: 'label',
    label: 'Label',
    component: 'input'
}

const componentProperties = {
    [componentTypes.TEXT_FIELD]: {
        attributes: [LABEL, IS_REQUIRED]
    },
    [componentTypes.PLAIN_TEXT]: {
        attributes: [LABEL],
        disableValidators: true,
        disableInitialValue: true
    }
}
```

**After**

Kapture 2021-05-06 at 09 06 16

### CODE REVIEW

**Review by Hyperkid123 — COMMENTED** [review]
@rvsia Maybe rather than disabling these separately, I would also add an `isInteractive` flag. This would be `true` by default and if se to false, it would have the same effect as setting new flasg to true.

It will encapsulate fields like tabs, sub forms, etc.

Other option that I am thinking about, is actually looking at the `registeredFields` array and compare the field name with the list. Fields that do not use `useFieldApi` (which this is targeting) will not be in the list, thus can't have initial value or validators.

**Comment by rvsia** [comment]
@Hyperkid123 

There are components that should have it separately. For example switch, you can disable validators for it but keep the initial value in your editor.

The second approach seems unnecessary complex to me.

I think providing more control is always better than doing some magic in the background.

**Comment by Hyperkid123** [comment]
@rvsia I don't want to delete the options you have added. Not at all. Having maximum control over the configuration is the ultimate goal.

The thing about the second approach is that it will match the renderer prop assignement. We now have an issue with adding `useFieldApi` specific attributes by default to a component that is not calling the hook. That should not happen. I should not be expected to disable attributes that are not event available for a component through the renderer. And obviously, I should not be required to enable attributes that are available via renderer. And if for some reason we want to show these even though they are useless we can still use the config options you have added as an override.

My goal is to eventually simplify the configuration and adding another mandatory configuration option just because the field is of a certain type does not help at all.

**Comment by rvsia** [comment]
@Hyperkid123 Ok, I added the automatic detection of registered fields.

**Review by Hyperkid123 — APPROVED** [review]

**Comment by Hyperkid123** [comment]
@rvsia we are just missing the form context in some tests.

**Pull request merged**
